#mysql Dockerfile

FROM mysql:5.7
MAINTAINER Nammu8395@gmail.com

ENV MYSQL_ROOT_PASSWORD="32121849"
\ MYSQL_DATABASE="Profile"
\ MYSQL_USER='Lee'
\ MYSQL_PASSWORD="32121849"
RUN rm /etc/my.cnf
COPY my.cnf /etc/my.cnf
EXPOSE 3306
